services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: allysonaguilera
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: checkvisit
    ports:
      - "5432:5432"
    volumes:
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: